spring:
  application:
    name: greeting-microservice
 
#Tomcat Embedded Server Configuration
server: 
  port: 0
 
#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
